-- Durable storage for the Imperium market intelligence cron.
-- The application accesses this table only from server-side service-role code.

create table if not exists public.market_snapshots (
  id uuid primary key default gen_random_uuid(),
  generated_at timestamptz not null default now(),
  market_regime text not null,
  source_status jsonb not null default '{}'::jsonb,
  picks jsonb not null default '[]'::jsonb,
  notes jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  constraint market_snapshots_source_status_object
    check (jsonb_typeof(source_status) = 'object'),
  constraint market_snapshots_picks_array
    check (jsonb_typeof(picks) = 'array'),
  constraint market_snapshots_notes_array
    check (jsonb_typeof(notes) = 'array')
);

-- The repository also contains an older numeric migration with this table.
-- Add the validation constraints when upgrading a database where that legacy
-- migration already created the relation.
do $migration$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'market_snapshots_source_status_object'
      and conrelid = 'public.market_snapshots'::regclass
  ) then
    alter table public.market_snapshots
      add constraint market_snapshots_source_status_object
      check (jsonb_typeof(source_status) = 'object');
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'market_snapshots_picks_array'
      and conrelid = 'public.market_snapshots'::regclass
  ) then
    alter table public.market_snapshots
      add constraint market_snapshots_picks_array
      check (jsonb_typeof(picks) = 'array');
  end if;

  if not exists (
    select 1
    from pg_constraint
    where conname = 'market_snapshots_notes_array'
      and conrelid = 'public.market_snapshots'::regclass
  ) then
    alter table public.market_snapshots
      add constraint market_snapshots_notes_array
      check (jsonb_typeof(notes) = 'array');
  end if;
end
$migration$;

create index if not exists idx_market_snapshots_generated_at
  on public.market_snapshots (generated_at desc);

alter table public.market_snapshots enable row level security;

-- Remove the permissive policies from the legacy numeric migration if this
-- migration is applied to a fresh database where that file ran first.
drop policy if exists "Anyone can view market snapshots"
  on public.market_snapshots;
drop policy if exists "Service role can manage market snapshots"
  on public.market_snapshots;

revoke all on table public.market_snapshots
  from public, anon, authenticated, service_role;
grant select, insert on table public.market_snapshots to service_role;

comment on table public.market_snapshots is
  'Service-only durable snapshots generated by the Imperium market intelligence cron.';
